/**
 * Interface for an error handler that can be used to handle errors in SmartNgRX.
 * This should be implemented by any service that wants to handle errors
 * generated by SmartNgRX.
 */
export interface SmartErrorHandler {
  /**
   * Handles an error.
   *
   * @param message The message to display to the user
   * @param error The error that occurred
   */
  handleError(message: string, error: unknown): void;
}
