onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
