# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm i
  DupCheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm dupcheck
  CheckFormatting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm format:check
  Lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm lint
  HtmlLint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm htmllint
  Build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm build
  UnitTests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pnpm test:coverage
  Documentation:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run update docs script
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        env:
          GH_PAGES_SMART_NGRX: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAGES_SMART_NGRX}@github.com/${{ github.repository }}.git
          .github/workflows/update_docs.sh
