name: Remove issue from project
on:
  issues:
    types:
      - closed

jobs:
  remove-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Issue from Project
      - uses: monry/actions-delete-issue-from-project@v2.0.1
        with:
          github-token: ${{ secrets.PROJECT_SECRET }}
          project-owner: 'DaveMBush'
          project-number: 1
          issue-repository: 'DaveMBush/dynamic-ngrx-test'
          issue-id: github.event.issue.node_id
