name: Remove issue from projects
on:
  issues:
    types:
      - closed

jobs:
  remove-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Remove issue from projects
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /projects/columns/cards/:card_id
          card_id: ${{ github.event.issue.project_card.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
