name: Remove issue from project
on:
  issues:
    types:
      - closed

jobs:
  remove-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Remove issue from project
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/projects/columns/cards/${{ github.event.issue.project_card.id }}"
